# Generated by Django 3.2 on 2021-05-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('albums', models.URLField()),
                ('tracks', models.URLField()),
                ('self_url', models.URLField()),
            ],
        ),
    ]
