# Generated by Django 3.2 on 2021-05-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='self_url',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='tracks',
        ),
    ]
