# Generated by Django 3.2 on 2021-05-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_artista_self_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='self_url',
        ),
    ]
