# Generated by Django 3.2 on 2021-05-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_artista_self_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='albums',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artista',
            name='self_url',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artista',
            name='tracks',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
