# Generated by Django 3.2 on 2021-05-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20210502_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='albums',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='artista',
            name='self_url',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='artista',
            name='tracks',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
