# Generated by Django 3.2 on 2021-05-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20210502_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='albums',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artista',
            name='self_url',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artista',
            name='tracks',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
