# Generated by Django 3.2 on 2021-05-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20210502_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
