# Generated by Django 3.2 on 2021-05-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_artista_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artista',
            new_name='Artist',
        ),
    ]
