# Generated by Django 3.2 on 2021-05-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_rename_artista_artist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Artista',
        ),
    ]
