# Generated by Django 3.2 on 2021-05-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_rename_artist_artista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artista',
            new_name='Artist',
        ),
    ]
