# Generated by Django 3.2 on 2021-05-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artist_id',
        ),
    ]
