# Generated by Django 3.2 on 2021-05-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
